---@diagnostic disable-next-line: undefined-global
local LSM = LibStub("LibSharedMedia-3.0")

if LSM == nil then return end

-- [[ Fonts ]] --
-- Gotham
LSM:Register("font", "Gotham Bold", [[Interface\Addons\CuttingEdgeMedia\Fonts\gotham-bold.ttf]])
LSM:Register("font", "Gotham Bold Italic", [[Interface\Addons\CuttingEdgeMedia\Fonts\gotham-bold-italic.ttf]])
LSM:Register("font", "Gotham Book", [[Interface\Addons\CuttingEdgeMedia\Fonts\gotham-book.ttf]])
LSM:Register("font", "Gotham Book Italic", [[Interface\Addons\CuttingEdgeMedia\Fonts\gotham-book-italic.ttf]])
LSM:Register("font", "Gotham Light", [[Interface\Addons\CuttingEdgeMedia\Fonts\gotham-light.ttf]])
LSM:Register("font", "Gotham Light Italic", [[Interface\Addons\CuttingEdgeMedia\Fonts\gotham-light-italic.ttf]])
LSM:Register("font", "Gotham Medium", [[Interface\Addons\CuttingEdgeMedia\Fonts\gotham-medium.ttf]])
LSM:Register("font", "Gotham Medium Italic", [[Interface\Addons\CuttingEdgeMedia\Fonts\gotham-medium-italic.ttf]])
LSM:Register("font", "Gotham Narrow Ultra", [[Interface\Addons\CuttingEdgeMedia\Fonts\gotham-narrow-ultra.ttf]])
-- Homizio
LSM:Register("font", "Homizio Black", [[Interface\Addons\CuttingEdgeMedia\Fonts\homizio-black.ttf]])
LSM:Register("font", "Homizio Bold", [[Interface\Addons\CuttingEdgeMedia\Fonts\homizio-bold.ttf]])
LSM:Register("font", "Homizio Light", [[Interface\Addons\CuttingEdgeMedia\Fonts\homizio-light.ttf]])
LSM:Register("font", "Homizio Medium", [[Interface\Addons\CuttingEdgeMedia\Fonts\homizio-medium.ttf]])
LSM:Register("font", "Homizio Regular", [[Interface\Addons\CuttingEdgeMedia\Fonts\homizio-regular.ttf]])
LSM:Register("font", "Homizio Thin", [[Interface\Addons\CuttingEdgeMedia\Fonts\homizio-thin.ttf]])
-- ITC Avant Garde Gothic
LSM:Register("font", "ITC Avant Garde Gothic", [[Interface\Addons\CuttingEdgeMedia\Fonts\itc-avant-garde-gothic.ttf]])
-- Montserrat
LSM:Register("font", "Montserrat Medium", [[Interface\Addons\CuttingEdgeMedia\Fonts\montserrat-medium.ttf]])
LSM:Register("font", "Montserrat Regular", [[Interface\Addons\CuttingEdgeMedia\Fonts\montserrat-regular.ttf]])
LSM:Register("font", "Montserrat SemiBold", [[Interface\Addons\CuttingEdgeMedia\Fonts\montserrat-semi-bold.ttf]])
-- Morpheus
LSM:Register("font", "Morpheus", [[Interface\Addons\CuttingEdgeMedia\Fonts\morpheus.ttf]])
-- Noto Sans
LSM:Register("font", "Noto Sans Condensed Medium", [[Interface\Addons\CuttingEdgeMedia\Fonts\notosans-condensed-medium.ttf]])
LSM:Register("font", "Noto Sans Condensed Regular", [[Interface\Addons\CuttingEdgeMedia\Fonts\notosans-condensed-regular.ttf]])
LSM:Register("font", "Noto Sans Condensed Semi Bold", [[Interface\Addons\CuttingEdgeMedia\Fonts\notosans-condensed-semi-bold.ttf]])
LSM:Register("font", "Noto Sans Extra Condensed Medium", [[Interface\Addons\CuttingEdgeMedia\Fonts\notosans-extra-condensed-medium.ttf]])
LSM:Register("font", "Noto Sans Extra Condensed Regular", [[Interface\Addons\CuttingEdgeMedia\Fonts\notosans-extra-condensed-regular.ttf]])
LSM:Register("font", "Noto Sans Extra Condensed Semi Bold", [[Interface\Addons\CuttingEdgeMedia\Fonts\notosans-extra-condensed-semi-bold.ttf]])
LSM:Register("font", "Noto Sans Medium", [[Interface\Addons\CuttingEdgeMedia\Fonts\notosans-medium.ttf]])
LSM:Register("font", "Noto Sans Regular", [[Interface\Addons\CuttingEdgeMedia\Fonts\notosans-regular.ttf]])
LSM:Register("font", "Noto Sans Semi Bold", [[Interface\Addons\CuttingEdgeMedia\Fonts\notosans-semi-bold.ttf]])
LSM:Register("font", "Noto Sans Semi Condensed Medium", [[Interface\Addons\CuttingEdgeMedia\Fonts\notosans-semi-condensed-medium.ttf]])
LSM:Register("font", "Noto Sans Semi Condensed Regular", [[Interface\Addons\CuttingEdgeMedia\Fonts\notosans-semi-condensed-regular.ttf]])
LSM:Register("font", "Noto Sans Semi Condensed Semi Bold", [[Interface\Addons\CuttingEdgeMedia\Fonts\notosans-semi-condensed-semi-bold.ttf]])
-- Play
LSM:Register("font", "Play Bold", [[Interface\Addons\CuttingEdgeMedia\Fonts\play-bold.ttf]])
LSM:Register("font", "Play Regular", [[Interface\Addons\CuttingEdgeMedia\Fonts\play-regular.ttf]])
-- Poppins
LSM:Register("font", "Poppins Medium", [[Interface\Addons\CuttingEdgeMedia\Fonts\poppins-medium.ttf]])
LSM:Register("font", "Poppins Regular", [[Interface\Addons\CuttingEdgeMedia\Fonts\poppins-regular.ttf]])
LSM:Register("font", "Poppins Semi Bold", [[Interface\Addons\CuttingEdgeMedia\Fonts\poppins-semi-bold.ttf]])
-- Roboto Mono
LSM:Register("font", "Roboto Mono Thin", [[Interface\Addons\CuttingEdgeMedia\Fonts\roboto-mono-thin.ttf]])
LSM:Register("font", "Roboto Mono Thin Italic", [[Interface\Addons\CuttingEdgeMedia\Fonts\roboto-mono-thin-italic.ttf]])
LSM:Register("font", "Roboto Mono Light", [[Interface\Addons\CuttingEdgeMedia\Fonts\roboto-mono-light.ttf]])
LSM:Register("font", "Roboto Mono Light Italic", [[Interface\Addons\CuttingEdgeMedia\Fonts\roboto-mono-light-italic.ttf]])
LSM:Register("font", "Roboto Mono", [[Interface\Addons\CuttingEdgeMedia\Fonts\roboto-mono-regular.ttf]])
LSM:Register("font", "Roboto Mono Italic", [[Interface\Addons\CuttingEdgeMedia\Fonts\roboto-mono-italic.ttf]])
LSM:Register("font", "Roboto Mono SemiBold", [[Interface\Addons\CuttingEdgeMedia\Fonts\roboto-mono-semi-bold.ttf]])
LSM:Register("font", "Roboto Mono SemiBold Italic", [[Interface\Addons\CuttingEdgeMedia\Fonts\roboto-mono-semi-bold-italic.ttf]])
-- Semplicita Pro
LSM:Register("font", "Semplicita Pro Bold Italic", [[Interface\Addons\CuttingEdgeMedia\Fonts\semplicita-pro-bold-italic.ttf]])
LSM:Register("font", "Semplicita Pro Bold", [[Interface\Addons\CuttingEdgeMedia\Fonts\semplicita-pro-bold.ttf]])
LSM:Register("font", "Semplicita Pro Italic", [[Interface\Addons\CuttingEdgeMedia\Fonts\semplicita-pro-italic.ttf]])
LSM:Register("font", "Semplicita Pro Light Italic", [[Interface\Addons\CuttingEdgeMedia\Fonts\semplicita-pro-light-italic.ttf]])
LSM:Register("font", "Semplicita Pro Light", [[Interface\Addons\CuttingEdgeMedia\Fonts\semplicita-pro-light.ttf]])
LSM:Register("font", "Semplicita Pro Medium Italic", [[Interface\Addons\CuttingEdgeMedia\Fonts\semplicita-pro-medium-italic.ttf]])
LSM:Register("font", "Semplicita Pro Medium", [[Interface\Addons\CuttingEdgeMedia\Fonts\semplicita-pro-medium.ttf]])
LSM:Register("font", "Semplicita Pro Regular", [[Interface\Addons\CuttingEdgeMedia\Fonts\semplicita-pro-regular.ttf]])
LSM:Register("font", "Semplicita Pro Semi Bold Italic", [[Interface\Addons\CuttingEdgeMedia\Fonts\semplicita-pro-semi-bold-italic.ttf]])
LSM:Register("font", "Semplicita Pro Semi Bold", [[Interface\Addons\CuttingEdgeMedia\Fonts\semplicita-pro-semi-bold.ttf]])
-- Vixar ASCI
LSM:Register("font", "Vixar ASCI", [[Interface\Addons\CuttingEdgeMedia\Fonts\vixar-asci.ttf]])

-- [[ Sounds ]] --
-- General
LSM:Register("sound", "|cFFeb6234CR|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\General\cr.ogg]])
LSM:Register("sound", "|cFFeb6234Dead|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\General\dead.ogg]])
LSM:Register("sound", "|cFFeb6234Disease|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\General\disease.ogg]])
LSM:Register("sound", "|cFFeb6234Healing Potion|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\General\healing-potion.ogg]])
LSM:Register("sound", "|cFFeb6234Healthstone|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\General\healthstone.ogg]])
LSM:Register("sound", "|cFFeb6234Mana-Potion|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\General\mana-potion.ogg]])
LSM:Register("sound", "|cFFeb6234Shield|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\General\shield.ogg]])
LSM:Register("sound", "|cFFeb6234Stun|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\General\stun.ogg]])
LSM:Register("sound", "|cFFeb6234Trap|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\General\trap.ogg]])
LSM:Register("sound", "|cFFeb6234Warning|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\General\warning.ogg]])
--- Money
---- Income
LSM:Register("sound", "|cFF89eb34Coin Alternate|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\General\Money\Income\coin-alternate.ogg]])
LSM:Register("sound", "|cFF89eb34Coin Alternate 2|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\General\Money\Income\coin-alternate-2.ogg]])
LSM:Register("sound", "|cFF89eb34Coin Big|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\General\Money\Income\coin-big.ogg]])
LSM:Register("sound", "|cFF89eb34Coin Normal|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\General\Money\Income\coin-normal.ogg]])
LSM:Register("sound", "|cFF89eb34Coin SemiNormal|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\General\Money\Income\coin-semi-normal.ogg]])
LSM:Register("sound", "|cFF89eb34Coin Sweet|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\General\Money\Income\coin-sweet.ogg]])
---- Expense
--- Externals
LSM:Register("sound", "|cFF03ffc4External Defensive|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\General\Externals\Defensive\lazy-bird.ogg]])
LSM:Register("sound", "|cFF03ffc4Bloodlust|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\General\Externals\Offensive\bloodlust.ogg]])
LSM:Register("sound", "|cFF03ffc4External Offensive|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\General\Externals\Offensive\happy-bird.ogg]])
LSM:Register("sound", "|cFF03ffc4External Utility|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\General\Externals\Utility\sweden-bird.ogg]])

-- Instances
--- Colors
LSM:Register("sound", "|cFFd408cdBlue|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Colors\blue.ogg]])
LSM:Register("sound", "|cFFd408cdGreen|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Colors\green.ogg]])
LSM:Register("sound", "|cFFd408cdOrange|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Colors\orange.ogg]])
LSM:Register("sound", "|cFFd408cdPurple|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Colors\purple.ogg]])
LSM:Register("sound", "|cFFd408cdRed|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Colors\red.ogg]])
LSM:Register("sound", "|cFFd408cdWhite|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Colors\white.ogg]])
LSM:Register("sound", "|cFFd408cdYellow|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Colors\yellow.ogg]])
--- Countdowns
LSM:Register("sound", "|cFFd408cd1|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Countdowns\1.ogg]])
LSM:Register("sound", "|cFFd408cd2|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Countdowns\2.ogg]])
LSM:Register("sound", "|cFFd408cd3|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Countdowns\3.ogg]])
LSM:Register("sound", "|cFFd408cd4|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Countdowns\4.ogg]])
LSM:Register("sound", "|cFFd408cd5|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Countdowns\5.ogg]])
LSM:Register("sound", "|cFFd408cd6|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Countdowns\6.ogg]])
LSM:Register("sound", "|cFFd408cd7|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Countdowns\7.ogg]])
LSM:Register("sound", "|cFFd408cd8|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Countdowns\8.ogg]])
LSM:Register("sound", "|cFFd408cd9|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Countdowns\9.ogg]])
LSM:Register("sound", "|cFFd408cd10|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Countdowns\10.ogg]])
LSM:Register("sound", "|cFFd408cdReady|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Countdowns\ready.ogg]])
--- Events
LSM:Register("sound", "|cFFd408cdAdd|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\add.ogg]])
LSM:Register("sound", "|cFFd408cdAdds|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\adds.ogg]])
LSM:Register("sound", "|cFFd408cdAoE|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\aoe.ogg]])
LSM:Register("sound", "|cFFd408cdAssist|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\assist.ogg]])
LSM:Register("sound", "|cFFd408cdAvoid|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\avoid.ogg]])
LSM:Register("sound", "|cFFd408cdBait|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\bait.ogg]])
LSM:Register("sound", "|cFFd408cdBeam|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\beam.ogg]])
LSM:Register("sound", "|cFFd408cdBackup|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\beckup.ogg]])
LSM:Register("sound", "|cFFd408cdBehind|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\behind.ogg]])
LSM:Register("sound", "|cFFd408cdBleed|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\bleed.ogg]])
LSM:Register("sound", "|cFFd408cdBoP|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\bop.ogg]])
LSM:Register("sound", "|cFFd408cdBreak|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\break.ogg]])
LSM:Register("sound", "|cFFd408cdBuff|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\buff.ogg]])
LSM:Register("sound", "|cFFd408cdBuffed|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\buffed.ogg]])
LSM:Register("sound", "|cFFd408cdCC|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\cc.ogg]])
LSM:Register("sound", "|cFFd408cdCenter|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\center.ogg]])
LSM:Register("sound", "|cFFd408cdChain|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\chain.ogg]])
LSM:Register("sound", "|cFFd408cdClear|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\clear.ogg]])
LSM:Register("sound", "|cFFd408cdCollect|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\collect.ogg]])
LSM:Register("sound", "|cFFd408cdDance|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\dance.ogg]])
LSM:Register("sound", "|cFFd408cdDead|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\dead.ogg]])
LSM:Register("sound", "|cFFd408cdDebuff|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\debuff.ogg]])
LSM:Register("sound", "|cFFd408cdDebuffed|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\debuffed.ogg]])
LSM:Register("sound", "|cFFd408cdDispell|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\dispell.ogg]])
LSM:Register("sound", "|cFFd408cdDodge|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\dodge.ogg]])
LSM:Register("sound", "|cFFd408cdDon't Move|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\dont-move.ogg]])
LSM:Register("sound", "|cFFd408cdDoT|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\dot.ogg]])
LSM:Register("sound", "|cFFd408cdDrop|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\drop.ogg]])
LSM:Register("sound", "|cFFd408cdEnter|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\enter.ogg]])
LSM:Register("sound", "|cFFd408cdFire|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\fire.ogg]])
LSM:Register("sound", "|cFFd408cdFixate|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\fixate.ogg]])
LSM:Register("sound", "|cFFd408cdFront|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\front.ogg]])
LSM:Register("sound", "|cFFd408cdFrontal|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\frontal.ogg]])
LSM:Register("sound", "|cFFd408cdGate|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\gate.ogg]])
LSM:Register("sound", "|cFFd408cdGather|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\gather.ogg]])
LSM:Register("sound", "|cFFd408cdHeal CD|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\heal-cd.ogg]])
LSM:Register("sound", "|cFFd408cdHide|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\hide.ogg]])
LSM:Register("sound", "|cFFd408cdHigh Energy|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\high-energy.ogg]])
LSM:Register("sound", "|cFFd408cdHigh Stacks|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\high-stacks.ogg]])
LSM:Register("sound", "|cFFd408cdImmunity|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\immunity.ogg]])
LSM:Register("sound", "|cFFd408cdIn|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\in.ogg]])
LSM:Register("sound", "|cFFd408cdIntermission|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\intermission.ogg]])
LSM:Register("sound", "|cFFd408cdInterrupt|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\interrupt.ogg]])
LSM:Register("sound", "|cFFd408cdInvisibility|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\invisibility.ogg]])
LSM:Register("sound", "|cFFd408cdKnock|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\knock.ogg]])
LSM:Register("sound", "|cFFd408cdLeft|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\left.ogg]])
LSM:Register("sound", "|cFFd408cdLinked|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\linked.ogg]])
LSM:Register("sound", "|cFFd408cdMagic", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\magic.ogg]])
LSM:Register("sound", "|cFFd408cdMelee|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\melee.ogg]])
LSM:Register("sound", "|cFFd408cdMove|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\move.ogg]])
LSM:Register("sound", "|cFFd408cdNext|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\next.ogg]])
LSM:Register("sound", "|cFFd408cdOrb|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\orb.ogg]])
LSM:Register("sound", "|cFFd408cdOut|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\out.ogg]])
LSM:Register("sound", "|cFFd408cdOverlap|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\overlap.ogg]])
LSM:Register("sound", "|cFFd408cdPhase 2|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\phase-2.ogg]])
LSM:Register("sound", "|cFFd408cdPhase 3|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\phase-3.ogg]])
LSM:Register("sound", "|cFFd408cdPhysical|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\physical.ogg]])
LSM:Register("sound", "|cFFd408cdPI|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\pi.ogg]])
LSM:Register("sound", "|cFFd408cdPS|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\ps.ogg]])
LSM:Register("sound", "|cFFd408cdRage|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\rage.ogg]])
LSM:Register("sound", "|cFFd408cdRange|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\range.ogg]])
LSM:Register("sound", "|cFFd408cdReflect|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\reflect.ogg]])
LSM:Register("sound", "|cFFd408cdRight|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\right.ogg]])
LSM:Register("sound", "|cFFd408cdSac|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\sac.ogg]])
LSM:Register("sound", "|cFFd408cdSelf CD|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\self-cd.1ogg]])
LSM:Register("sound", "|cFFd408cdSoak|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\soak.ogg]])
LSM:Register("sound", "|cFFd408cdSoon|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\soon.ogg]])
LSM:Register("sound", "|cFFd408cdSpawn|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\spawn.ogg]])
LSM:Register("sound", "|cFFd408cdSpellsteal|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\spellsteal.ogg]])
LSM:Register("sound", "|cFFd408cdSplit|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\split.ogg]])
LSM:Register("sound", "|cFFd408cdSpread|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\spread.ogg]])
LSM:Register("sound", "|cFFd408cdStack|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\stack.ogg]])
LSM:Register("sound", "|cFFd408cdStop Cast|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\stop-cast.ogg]])
LSM:Register("sound", "|cFFd408cdStop|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\stop.ogg]])
LSM:Register("sound", "|cFFd408cdSwitch|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\switch.ogg]])
LSM:Register("sound", "|cFFd408cdTargeted|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\targeted.ogg]])
LSM:Register("sound", "|cFFd408cdTaunt|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\taunt.ogg]])
LSM:Register("sound", "|cFFd408cdTransition|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\transition.ogg]])
LSM:Register("sound", "|cFFd408cdTurn|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\turn.ogg]])
LSM:Register("sound", "|cFFd408cdWave|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Events\wave.ogg]])
--- Marks
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_1:16|t", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Marks\star.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_2:16|t", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Marks\circle.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_3:16|t", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Marks\diamond.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_4:16|t", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Marks\triangle.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_5:16|t", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Marks\moon.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_6:16|t", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Marks\square.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_7:16|t", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Marks\cross.ogg]])
LSM:Register("sound", "|TInterface\\TargetingFrame\\UI-RaidTargetingIcon_8:16|t", [[Interface\Addons\CuttingEdgeMedia\Sounds\Instances\Marks\skull.ogg]])

-- Classes
--- Durid
LSM:Register("sound", "|cFFFF7C0ABuff Missing|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Classes\Druid\buff-missing.ogg]])
LSM:Register("sound", "|cFFFF7C0ARebirth|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Classes\Druid\rebirth.ogg]])
LSM:Register("sound", "|cFFFF7C0ARenewal|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Classes\Druid\renewal.ogg]])
---- Restoration
LSM:Register("sound", "|cFFFF7C0AAdaptive Swarm|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Classes\Druid\Restoration\adaptive-swarm-1.ogg]])
LSM:Register("sound", "|cFFFF7C0AAdaptive Swarm 2|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Classes\Druid\Restoration\adaptive-swarm-2.ogg]])
LSM:Register("sound", "|cFFFF7C0AClearcasting|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Classes\Druid\Restoration\clearcasting.ogg]])
LSM:Register("sound", "|cFFFF7C0AFlourish|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Classes\Druid\Restoration\flourish.ogg]])
LSM:Register("sound", "|cFFFF7C0AInnervate|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Classes\Druid\Restoration\innervate.ogg]])
LSM:Register("sound", "|cFFFF7C0AInnervated|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Classes\Druid\Restoration\innervated.ogg]])
LSM:Register("sound", "|cFFFF7C0AIronwood|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Classes\Druid\Restoration\ironwood.ogg]])
LSM:Register("sound", "|cFFFF7C0ALifebloom|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Classes\Druid\Restoration\lifebloom.ogg]])
-- Mage
--- Fire
LSM:Register("sound", "|cFF3FC7EBCombustion Incoming|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Classes\Mage\Fire\combustion-active.ogg]])
-- Warlock
--- Destruction
LSM:Register("sound", "|cFF8788EEInfernal|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Classes\Warlock\Destruction\infernal.ogg]])
LSM:Register("sound", "|cFF8788EEInfernal Incoming|r", [[Interface\Addons\CuttingEdgeMedia\Sounds\Classes\Warlock\Destruction\infernal-active.ogg]])

-- [[ Statusbars ]] --
LSM:Register("statusbar", "Cutting Edge", [[Interface\Addons\CuttingEdgeMedia\Statusbars\cutting-edge-default.tga]])
LSM:Register("statusbar", "Cutting Edge Stripped", [[Interface\Addons\CuttingEdgeMedia\Statusbars\cutting-edge-stripped.tga]])
LSM:Register("statusbar", "Cutting Edge Stripped (Plater)", [[Interface\Addons\CuttingEdgeMedia\Statusbars\cutting-edge-stripped-2.tga]])
