name: Create Release

on:
  push:
    branches:
      - stage
    tags:
      - "*"
    paths-ignore:
      - ".github/**"
      - ".git/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout addon
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Package
        uses: BigWigsMods/packager@master
        with:
          args: -u -g retail -p 883772 -a Q6aE9A6W -n "{package-name}-{game-type}"
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
